-- ═══════════════════════════════════════════════════════
-- Level Up Interviews — Supabase Schema
-- Run this in Supabase SQL Editor (Dashboard > SQL)
-- ═══════════════════════════════════════════════════════

-- 1. Profiles (extends auth.users)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  name text not null default '',
  email text not null default '',
  target_role text default '',
  target_company text default '',
  industry text default '',
  interview_date text default '',
  experience_level text default '',
  learning_style text default 'direct',
  resume_file_name text default '',
  resume_text text default '',
  practice_timestamps jsonb default '[]'::jsonb,
  avatar_url text default '',
  subscription_tier text default 'free' check (subscription_tier in ('free', 'starter', 'pro')),
  subscription_start timestamptz,
  subscription_end timestamptz,
  cancel_at_period_end boolean default false,
  subscription_paused boolean default false,
  razorpay_payment_id text,
  razorpay_subscription_id text,
  has_completed_onboarding boolean default false,
  referral_code text unique,
  referred_by text,
  preferred_session_length integer,
  interview_types jsonb default '[]'::jsonb,
  resume_data jsonb,
  created_at timestamptz default now()
);

-- 2. Interview sessions
create table if not exists sessions (
  id text primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  date timestamptz default now(),
  type text not null,
  difficulty text not null,
  focus text default '',
  duration integer default 0,
  score integer default 0,
  questions integer default 0,
  transcript jsonb default '[]'::jsonb,
  ai_feedback text default '',
  skill_scores jsonb,
  -- Results report (generated by /api/evaluate-session, cached for re-open)
  report_json jsonb,
  report_version text default 'mvp-1',
  report_generated_at timestamptz,
  created_at timestamptz default now()
);
-- Ensure additive columns exist on upgrades (safe, idempotent)
alter table sessions add column if not exists report_json jsonb;
alter table sessions add column if not exists report_version text default 'mvp-1';
alter table sessions add column if not exists report_generated_at timestamptz;
create index if not exists idx_sessions_report_generated on sessions(report_generated_at);

-- 3. Calendar events
create table if not exists calendar_events (
  id text primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null,
  company text default '',
  date text not null,
  time text default '',
  type text default 'interview',
  notes text default '',
  created_at timestamptz default now()
);

-- 4. Feedback
create table if not exists feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  session_id text references sessions(id) on delete cascade not null,
  rating text check (rating in ('helpful', 'too_harsh', 'too_generous', 'inaccurate')) not null,
  comment text default '',
  session_score integer default 0,
  session_type text default '',
  created_at timestamptz default now()
);

-- 5. Payments
create table if not exists payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  razorpay_payment_id text unique not null,
  razorpay_order_id text default '',
  plan text not null,
  tier text not null,
  amount integer not null,
  currency text default 'INR',
  status text default 'completed',
  subscription_start timestamptz,
  subscription_end timestamptz,
  created_at timestamptz default now()
);

-- ═══════════════════════════════════════════════════════
-- Performance Indexes
-- ═══════════════════════════════════════════════════════

create index if not exists idx_profiles_tier_end on profiles(subscription_tier, subscription_end);
create index if not exists idx_sessions_user_created on sessions(user_id, created_at);
create index if not exists idx_sessions_user_date on sessions(user_id, date);
create index if not exists idx_payments_razorpay_id on payments(razorpay_payment_id);
create index if not exists idx_calendar_events_user on calendar_events(user_id, date);
create index if not exists idx_feedback_session on feedback(session_id);

-- ═══════════════════════════════════════════════════════
-- 6. Referral codes
-- ═══════════════════════════════════════════════════════

create table if not exists referrals (
  id uuid primary key default gen_random_uuid(),
  referrer_id uuid references profiles(id) on delete cascade not null,
  referral_code text unique not null,
  referred_email text,
  referred_id uuid references profiles(id) on delete set null,
  status text default 'pending' check (status in ('pending', 'redeemed', 'rewarded')),
  reward_granted boolean default false,
  created_at timestamptz default now()
);

create index if not exists idx_referrals_code on referrals(referral_code);
create index if not exists idx_referrals_referrer on referrals(referrer_id);

-- 7. Promo / coupon codes
create table if not exists promo_codes (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  discount_percent integer default 0 check (discount_percent between 0 and 100),
  discount_amount integer default 0,
  valid_from timestamptz default now(),
  valid_until timestamptz,
  max_uses integer default 0,
  current_uses integer default 0,
  applicable_plans text[] default '{}',
  created_at timestamptz default now()
);

create index if not exists idx_promo_codes_code on promo_codes(code);

-- 8. LLM usage tracking
create table if not exists llm_usage (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete set null,
  endpoint text not null,          -- 'generate' | 'follow-up' | 'evaluate' | 'analyze-resume'
  model text not null,             -- 'llama-3.3-70b-versatile' | 'gemini-2.0-flash' etc.
  is_fallback boolean default false,
  prompt_tokens integer default 0,
  completion_tokens integer default 0,
  total_tokens integer default 0,
  latency_ms integer default 0,
  status text default 'success' check (status in ('success', 'error', 'timeout')),
  error_message text,
  created_at timestamptz default now()
);

create index if not exists idx_llm_usage_user_created on llm_usage(user_id, created_at);
create index if not exists idx_llm_usage_endpoint on llm_usage(endpoint, created_at);
create index if not exists idx_llm_usage_created on llm_usage(created_at);

-- 9. Role competencies + company guidance
--
-- Mirrors the ROLE_COMPETENCIES + COMPANY_GUIDANCE maps currently hardcoded
-- in server-handlers/generate-questions.ts. The in-code constants are still
-- the source of truth; generate-questions.ts falls back to them when the DB
-- row is absent. Purpose: allow non-deploy updates, versioning, and eventual
-- A/B testing of question prompts per role/company.
--
-- Seeding is a separate migration step — creating the tables here is safe on
-- an empty DB because the fallback path keeps behaviour unchanged.
create table if not exists role_competencies (
  role_slug text primary key,
  body text not null,
  version integer default 1,
  updated_at timestamptz default now()
);
create table if not exists company_guidance (
  company_slug text primary key,
  body text not null,
  version integer default 1,
  updated_at timestamptz default now()
);
alter table role_competencies enable row level security;
alter table company_guidance enable row level security;
drop policy if exists "Anyone can read role competencies" on role_competencies;
create policy "Anyone can read role competencies" on role_competencies for select using (true);
drop policy if exists "Anyone can read company guidance" on company_guidance;
create policy "Anyone can read company guidance" on company_guidance for select using (true);
-- Writes only via service role (bypasses RLS). No INSERT/UPDATE/DELETE policy
-- for authenticated users — this data is admin-controlled.

-- 10. Story Notebook — saved STAR stories from interview results reports
create table if not exists story_notebook (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references profiles(id) on delete cascade not null,
  session_id text references sessions(id) on delete set null,
  question_idx integer,
  title text,
  question text,
  answer_text text,
  star jsonb,
  tags text[] default '{}',
  created_at timestamptz default now(),
  last_used_at timestamptz
);

create index if not exists idx_story_notebook_user on story_notebook(user_id, created_at desc);
alter table story_notebook enable row level security;
drop policy if exists "Users manage own stories" on story_notebook;
create policy "Users manage own stories" on story_notebook
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ═══════════════════════════════════════════════════════
-- Row Level Security (RLS)
-- Users can only access their own data
-- ═══════════════════════════════════════════════════════

-- Weekly-summary cron uses this to rate-limit emails per user.
alter table profiles add column if not exists last_summary_email_at timestamptz;

-- Bonus-session economy. Credits are granted by:
--   (a) One-time single-session purchase (verify-payment.ts)
--   (b) Streak milestones (save-session.ts — 7/14/30-day)
--   (c) Successful referrals (verify-payment.ts, when referee pays)
-- They are consumed by decrementSessionCredit() after a free-tier user exceeds
-- the 3-session free limit. Paid tiers ignore this column.
alter table profiles add column if not exists session_credits integer default 0;

-- Tracks the highest streak milestone the user has already been rewarded for
-- (7, 14, 30). Prevents double-grants when a user hovers around a milestone
-- after a missed day + resume. Value 0 means "no reward granted yet".
alter table profiles add column if not exists last_streak_reward_day integer default 0;

-- Re-engagement cron uses this to rate-limit emails per user (see re-engage-users.ts).
alter table profiles add column if not exists re_engage_sent timestamptz;

alter table profiles enable row level security;
alter table sessions enable row level security;
alter table calendar_events enable row level security;
alter table feedback enable row level security;
alter table payments enable row level security;

-- Profiles: users can read/update their own profile
create policy "Users can view own profile" on profiles
  for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles
  for update using (auth.uid() = id);
create policy "Users can insert own profile" on profiles
  for insert with check (auth.uid() = id);

-- Sessions: users can CRUD their own sessions
create policy "Users can view own sessions" on sessions
  for select using (auth.uid() = user_id);
create policy "Users can insert own sessions" on sessions
  for insert with check (auth.uid() = user_id);
create policy "Users can delete own sessions" on sessions
  for delete using (auth.uid() = user_id);

-- Calendar: users can CRUD their own events
create policy "Users can view own events" on calendar_events
  for select using (auth.uid() = user_id);
create policy "Users can insert own events" on calendar_events
  for insert with check (auth.uid() = user_id);
create policy "Users can delete own events" on calendar_events
  for delete using (auth.uid() = user_id);
create policy "Users can update own events" on calendar_events
  for update using (auth.uid() = user_id);

-- Feedback: users can CRUD their own feedback
create policy "Users can view own feedback" on feedback
  for select using (auth.uid() = user_id);
create policy "Users can insert own feedback" on feedback
  for insert with check (auth.uid() = user_id);
create policy "Users can update own feedback" on feedback
  for update using (auth.uid() = user_id);
create policy "Users can delete own feedback" on feedback
  for delete using (auth.uid() = user_id);

-- Payments: users can only view their own payments (insert via service role only)
create policy "Users can view own payments" on payments
  for select using (auth.uid() = user_id);

-- Referrals: users can view/create their own referrals
alter table referrals enable row level security;
create policy "Users can view own referrals" on referrals
  for select using (auth.uid() = referrer_id);
create policy "Users can insert own referrals" on referrals
  for insert with check (auth.uid() = referrer_id);

-- Promo codes: anyone can read (validation is server-side)
alter table promo_codes enable row level security;
create policy "Anyone can view promo codes" on promo_codes
  for select using (true);

-- LLM usage: users can view their own usage (insert via service role only)
alter table llm_usage enable row level security;
create policy "Users can view own llm usage" on llm_usage
  for select using (auth.uid() = user_id);
-- Explicit INSERT policy as a safety net. The `service_role` key bypasses RLS
-- by design, but if SUPABASE_SERVICE_ROLE_KEY is ever misconfigured (e.g. set
-- to the anon key instead), writes would silently fail with a 401/403. This
-- allows service_role to insert regardless of bypass behavior.
drop policy if exists "Service role can insert llm usage" on llm_usage;
create policy "Service role can insert llm usage" on llm_usage
  for insert to service_role with check (true);

-- ═══════════════════════════════════════════════════════
-- Auto-create profile on signup
-- ═══════════════════════════════════════════════════════

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'full_name', '')
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger: fire after signup
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
