import { useState, useEffect, useCallback } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { c, font } from "./tokens";
import { useAuth } from "./AuthContext";
import { getSessionById, type SessionRecord } from "./supabase";

const RESULTS_KEY = "levelup_sessions";

function scoreLabelColor(score: number) {
  if (score >= 85) return c.sage;
  if (score >= 70) return c.gilt;
  return c.ember;
}

function scoreLabel(score: number) {
  if (score >= 85) return "Strong";
  if (score >= 70) return "Good";
  return "Developing";
}

function normalizeType(type: string): string {
  const map: Record<string, string> = {
    behavioral: "Behavioral", strategic: "Strategic",
    "technical-leadership": "Technical Leadership", "case-study": "Case Study",
    technical: "Technical", case: "Case Study",
  };
  return map[type] || type;
}

interface LocalSession {
  id: string;
  date: string;
  type: string;
  difficulty: string;
  focus: string;
  duration: number;
  score: number;
  questions: number;
  transcript?: { speaker: string; text: string; time?: string }[];
  ai_feedback?: string;
  skill_scores?: Record<string, number> | null;
}

function loadLocalSession(id: string): LocalSession | null {
  try {
    const raw = localStorage.getItem(RESULTS_KEY);
    if (!raw) return null;
    const sessions: LocalSession[] = JSON.parse(raw);
    return sessions.find(s => s.id === id) || null;
  } catch {
    return null;
  }
}

export default function SessionDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { user } = useAuth();
  const [session, setSession] = useState<LocalSession | null>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!id) { setLoading(false); return; }

    // Try localStorage first
    const local = loadLocalSession(id);
    if (local) {
      setSession(local);
      setLoading(false);
      return;
    }

    // Try Supabase
    if (user?.id) {
      getSessionById(id, user.id).then(record => {
        if (record) {
          setSession({
            id: record.id,
            date: record.date,
            type: record.type,
            difficulty: record.difficulty,
            focus: record.focus,
            duration: record.duration,
            score: record.score,
            questions: record.questions,
            transcript: record.transcript,
            ai_feedback: record.ai_feedback,
            skill_scores: record.skill_scores,
          });
        }
        setLoading(false);
      }).catch(() => setLoading(false));
    } else {
      setLoading(false);
    }
  }, [id, user?.id]);

  const dateObj = session ? new Date(session.date) : null;
  const dateLabel = dateObj ? dateObj.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) : "";
  const durationMin = session ? Math.ceil(session.duration / 60) : 0;
  const type = session ? normalizeType(session.type) : "";

  const generateExportText = useCallback(() => {
    if (!session) return "";
    const lines = [
      "LEVEL UP INTERVIEWS — SESSION REPORT",
      "━".repeat(40),
      `Type: ${type}`,
      `Date: ${dateLabel}`,
      `Duration: ${durationMin} min`,
      `Difficulty: ${session.difficulty}`,
      `Score: ${session.score}/100 (${scoreLabel(session.score)})`,
      "",
    ];
    if (session.skill_scores) {
      lines.push("SKILL SCORES");
      Object.entries(session.skill_scores).forEach(([name, score]) => {
        lines.push(`  ${name}: ${score}/100`);
      });
      lines.push("");
    }
    if (session.transcript && session.transcript.length > 0) {
      lines.push("TRANSCRIPT");
      session.transcript.forEach(msg => {
        lines.push(`${msg.speaker === "ai" ? "INTERVIEWER" : "CANDIDATE"}: ${msg.text}`);
        lines.push("");
      });
    }
    if (session.ai_feedback) {
      lines.push("AI FEEDBACK");
      lines.push(session.ai_feedback);
      lines.push("");
    }
    lines.push("━".repeat(40));
    lines.push("Generated by Level Up Interviews");
    return lines.join("\n");
  }, [session, type, dateLabel, durationMin]);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(generateExportText()).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [generateExportText]);

  const handleDownload = useCallback(() => {
    if (!session) return;
    const blob = new Blob([generateExportText()], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `LevelUp_Session_${session.date.split("T")[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, [generateExportText, session]);

  if (loading) {
    return (
      <div style={{ minHeight: "100vh", background: c.obsidian, display: "flex", alignItems: "center", justifyContent: "center" }}>
        <div style={{ width: 40, height: 40, border: `2px solid ${c.border}`, borderTopColor: c.gilt, borderRadius: "50%", animation: "spin 0.8s linear infinite" }} />
        <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
      </div>
    );
  }

  if (!session) {
    return (
      <div style={{ minHeight: "100vh", background: c.obsidian, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", fontFamily: font.ui }}>
        <p style={{ fontSize: 18, color: c.ivory, marginBottom: 8 }}>Session not found</p>
        <p style={{ fontSize: 13, color: c.stone, marginBottom: 24 }}>This session may have been deleted or the link is invalid.</p>
        <button onClick={() => navigate("/dashboard")} style={{ padding: "10px 24px", borderRadius: 8, border: "none", background: c.gilt, color: c.obsidian, fontSize: 13, fontWeight: 600, cursor: "pointer" }}>
          Back to Dashboard
        </button>
      </div>
    );
  }

  return (
    <div style={{ minHeight: "100vh", background: c.obsidian, fontFamily: font.ui, padding: "40px 24px" }}>
      <div style={{ maxWidth: 800, margin: "0 auto" }}>
        {/* Header */}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 }}>
          <button onClick={() => navigate("/dashboard")} style={{
            display: "flex", alignItems: "center", gap: 8, fontSize: 13, color: c.stone,
            background: "none", border: "none", cursor: "pointer", outline: "none",
          }}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="15 18 9 12 15 6"/></svg>
            Back to Dashboard
          </button>
          <div style={{ display: "flex", gap: 8 }}>
            <button onClick={handleCopy} aria-label="Copy report to clipboard" style={{
              padding: "7px 14px", borderRadius: 8, fontSize: 12, fontWeight: 500,
              background: "transparent", border: `1px solid ${c.border}`, color: c.stone,
              cursor: "pointer", display: "flex", alignItems: "center", gap: 6,
            }}>
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
              {copied ? "Copied!" : "Copy"}
            </button>
            <button onClick={handleDownload} aria-label="Download session report" style={{
              padding: "7px 14px", borderRadius: 8, fontSize: 12, fontWeight: 500,
              background: "transparent", border: `1px solid ${c.border}`, color: c.stone,
              cursor: "pointer", display: "flex", alignItems: "center", gap: 6,
            }}>
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
              Download
            </button>
          </div>
        </div>

        {/* Session summary card */}
        <div style={{ background: c.graphite, borderRadius: 14, border: `1px solid ${c.border}`, padding: "28px 32px", marginBottom: 20 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 20, flexWrap: "wrap", gap: 16 }}>
            <div>
              <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 8 }}>
                <span style={{ fontSize: 10, fontWeight: 600, letterSpacing: "0.08em", textTransform: "uppercase", color: c.gilt, background: "rgba(201,169,110,0.08)", padding: "4px 10px", borderRadius: 4 }}>{type}</span>
                <span style={{ fontSize: 13, color: c.stone }}>{dateLabel} · {durationMin} min</span>
              </div>
              <h2 style={{ fontSize: 22, fontWeight: 600, color: c.ivory, marginBottom: 4 }}>{session.focus || type} Interview</h2>
              {session.difficulty && <span style={{ fontSize: 12, color: c.stone, textTransform: "capitalize" }}>{session.difficulty} difficulty</span>}
            </div>
            <div style={{ textAlign: "center" }}>
              <div style={{ width: 72, height: 72, borderRadius: "50%", border: `3px solid ${scoreLabelColor(session.score)}`, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center" }}>
                <span style={{ fontFamily: font.mono, fontSize: 26, fontWeight: 700, color: c.ivory, lineHeight: 1 }}>{session.score}</span>
                <span style={{ fontSize: 10, fontWeight: 600, color: scoreLabelColor(session.score), marginTop: 2 }}>{scoreLabel(session.score)}</span>
              </div>
            </div>
          </div>

          {/* Skill scores */}
          {session.skill_scores && Object.keys(session.skill_scores).length > 0 && (
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 10, marginTop: 16 }}>
              {Object.entries(session.skill_scores).map(([name, score]) => (
                <div key={name} style={{ padding: "12px 14px", borderRadius: 10, background: c.obsidian, border: `1px solid ${c.border}` }}>
                  <span style={{ fontSize: 11, color: c.stone, display: "block", marginBottom: 6 }}>{name}</span>
                  <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                    <div style={{ flex: 1, height: 4, borderRadius: 2, background: c.border }}>
                      <div style={{ width: `${score}%`, height: "100%", borderRadius: 2, background: scoreLabelColor(score) }} />
                    </div>
                    <span style={{ fontFamily: font.mono, fontSize: 12, fontWeight: 600, color: c.ivory }}>{score}</span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Transcript */}
        {session.transcript && session.transcript.length > 0 && (
          <div style={{ background: c.graphite, borderRadius: 14, border: `1px solid ${c.border}`, padding: "28px 32px", marginBottom: 20 }}>
            <h3 style={{ fontSize: 15, fontWeight: 600, color: c.ivory, marginBottom: 20 }}>Full Transcript</h3>
            <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
              {session.transcript.map((msg, i) => (
                <div key={i} style={{ display: "flex", gap: 12, flexDirection: msg.speaker === "user" ? "row-reverse" : "row" }}>
                  <div style={{
                    width: 32, height: 32, borderRadius: "50%", flexShrink: 0,
                    background: msg.speaker === "ai" ? "rgba(201,169,110,0.1)" : "rgba(122,158,126,0.1)",
                    border: `1px solid ${msg.speaker === "ai" ? "rgba(201,169,110,0.2)" : "rgba(122,158,126,0.2)"}`,
                    display: "flex", alignItems: "center", justifyContent: "center",
                  }}>
                    {msg.speaker === "ai" ? (
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={c.gilt} strokeWidth="2"><circle cx="12" cy="12" r="3"/><path d="M12 1v2m0 18v2m-9-11h2m18 0h2M5.6 5.6l1.4 1.4m9.9 9.9l1.4 1.4M5.6 18.4l1.4-1.4m9.9-9.9l1.4-1.4"/></svg>
                    ) : (
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={c.sage} strokeWidth="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
                    )}
                  </div>
                  <div style={{ maxWidth: "75%", minWidth: 0 }}>
                    <div style={{
                      padding: "12px 16px", borderRadius: 12, fontSize: 13, color: c.chalk, lineHeight: 1.6,
                      background: msg.speaker === "ai" ? c.obsidian : "rgba(122,158,126,0.04)",
                      border: `1px solid ${msg.speaker === "ai" ? c.border : "rgba(122,158,126,0.1)"}`,
                      borderTopLeftRadius: msg.speaker === "ai" ? 4 : 12,
                      borderTopRightRadius: msg.speaker === "user" ? 4 : 12,
                    }}>
                      {msg.text}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* AI Feedback */}
        {session.ai_feedback && (
          <div style={{ background: c.graphite, borderRadius: 14, border: `1px solid ${c.border}`, padding: "28px 32px" }}>
            <h3 style={{ fontSize: 15, fontWeight: 600, color: c.ivory, marginBottom: 12 }}>AI Coach Summary</h3>
            <p style={{ fontSize: 14, color: c.chalk, lineHeight: 1.7, margin: 0, whiteSpace: "pre-wrap" }}>{session.ai_feedback}</p>
          </div>
        )}
      </div>
    </div>
  );
}
